version: "3.9"

services:
  brandscout:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: brandscout-api
    ports:
      - "8080:8080"
    environment:
      - REST_PORT=:8080